# make sure the k8s_monitor folder exists
- name: ensures destination dir exists
  file: 
    path: "{{ work_dir }}/k8s_monitor"
    state: directory

- name: copy k8s files
  template:
    src: files/{{ item }}
    dest: "{{ work_dir }}/k8s_monitor/{{ item }}"
    force: yes
  loop: "{{ k8s_files }}"

- name: Create and start k8s monitor
  shell:
    chdir: "{{ work_dir }}/k8s_monitor"
    cmd: kubectl apply -f {{ item }}
  loop: "{{ k8s_files }}"

