apiVersion: v1
kind: Service
metadata:
  name: longhorn-svc
  namespace: {{ k8s_namespace }}
spec:
  selector:
    app: longhorn-ui
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http