# file: playbook.yml
- name: Setup k3d cluster
  hosts:
  - pi_5

  vars:
    dest_path: "{{ lookup('env', 'HOME') }}/workspace"
    k3d_app: "/usr/local/bin/k3d"
    k8s_file: "nginx-svc-deploy.yml"
  become: true
  tasks:
    # enable cgroup memory
    - name: Set cgroup on Raspberry pi 5
      lineinfile:
        path: /boot/firmware/cmdline.txt
        regexp: '^(.*rootwait)$'
        line: '\1 cgroup_memory=1 cgroup_enable=memory'
        backrefs: true
      when: ( ansible_facts.architecture is search "arm" )
      notify:
        - Reboot pi5
    # copy required config files to remote
    - name: ensures destination dir exists
      file: 
        path: "{{ dest_path }}"
        state: directory
    # add files to destination dir
    - name: Copy config files to remote
      copy:
        src: "resources/"
        dest: "{{ dest_path }}"
        force: yes

    # install apt packages
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true
    - name: Install required packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - docker.io
          - docker-compose
          - python3-pip
        state: latest
        update_cache: true
    - name: adding existing user "{{ ansible_user }}" to group sudo
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      become: yes
    # install kubectl if not existing
    - name: Check if kubectl is installed
      stat:
        path: "/usr/local/bin/kubectl"
      register: kubectl
    - name: Download the latest kubectl release
      uri:
        url: "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/arm64/kubectl"
        dest: "/usr/local/bin/kubectl"
        mode: '0755'
      when: kubectl.stat.exists == False
    # install k3d if not existing
    - name: Check if k3d is installed
      stat:
        path: "{{ k3d_app }}"
      register: k3d
    - name: Install k3d if not existing
      get_url: 
        url: https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh dest=/tmp/k3d-installer.sh
      when: k3d.stat.exists == False
    - name: Install k3d
      shell: /tmp/k3d-installer.sh
      when: k3d.stat.exists == False
    - name: Remove the k3d-installer.sh
      file: 
        path: /tmp/k3d-installer.sh 
        state: absent

    - name: Check if k3d cluster is exist
      shell: "k3d cluster list | grep -v NAME | awk {'print $1'}"
      register: k3d_output
    - name: Print k3d result
      debug:
        msg: "{{ k3d_output.stdout }}"

  handlers:
    - name: reboot pi5
      reboot:

#ansible-playbook -i hosts playbook.yml --ask-pass --ask-become-pass
