---
# SSD PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ssd-pv-mariadb
  labels:
    type: local-ssd
spec:
  storageClassName: manual
  volumeMode: Filesystem # Filesystem|Block. Filesystem is the default mode if the volume mode is not defined.
  capacity:
    storage: 10Gi
  accessModes:
    #ReadWriteOnce -- the volume can be mounted as read-write by a single node
    #ReadOnlyMany -- the volume can be mounted read-only by many nodes
    #ReadWriteMany -- the volume can be mounted as read-write by many nodes
    - ReadWriteMany 
  hostPath:
    path: "/ssd/mariadb" # new sub-folder under cluster mount folder

# create PVC
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssd-pvc-mariadb
spec:
  storageClassName: manual # must match PV specification to be successfully bound together
  accessModes:
    - ReadWriteMany # must be compatible with the access modes supported by the PV.
  resources:
    requests:
      storage: 10Gi
---
#kubectl create service clusterip nginx --tcp=80:80
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service # for binding with ingress
spec:
  selector:
    app: mariadb # equality of matchLabels, get target pods
  ports:
    - protocol: TCP
      port: 3306 # service port
      targetPort: 3306 # pod port
  type: LoadBalancer

---
# mariadb-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-statefulset
spec:
  serviceName: mariadb-service
  replicas: 3
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      volumes:
        - name: mariadb-storage
          persistentVolumeClaim:
            claimName: ssd-pvc-mariadb
      containers:
        - name: mariadb
          image: arm64v8/mariadb
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: bmV4dGNsb3Vk
            - name: MYSQL_DATABASE
              value: mariadb
            - name: MYSQL_USER
              value: mariadb
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mariadb-storage
      restartPolicy: Always
      nodeSelector:
        disk: ssd
