---
# SSD PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ssd-pv-echo
  labels:
    type: local-ssd
spec:
  storageClassName: manual
  volumeMode: Filesystem # Filesystem|Block. Filesystem is the default mode if the volume mode is not defined.
  capacity:
    storage: 10Mi
  accessModes:
    #ReadWriteOnce -- the volume can be mounted as read-write by a single node
    #ReadOnlyMany -- the volume can be mounted read-only by many nodes
    #ReadWriteMany -- the volume can be mounted as read-write by many nodes
    - ReadWriteOnce 
  hostPath:
    path: "/ssd/echo" # new sub-folder under cluster mount folder
---
# Data PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv-echo
  labels:
    type: local-hdd
spec:
  storageClassName: manual
  capacity:
    storage: 20Mi
  accessModes:
    - ReadWriteMany # the volume can be mounted as read-write by many nodes.
  hostPath:
    path: "/data/echo" # new sub-folder under cluster mount folder

# create PVC
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssd-pvc-echo
spec:
  storageClassName: manual # must match PV specification to be successfully bound together
  accessModes:
    - ReadWriteOnce # must be compatible with the access modes supported by the PV.
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc-echo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Mi

# deploy a busybox
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  labels:
    app: busybox
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: echo
    spec:
      volumes:
        - name: echo-vol-ssd
          persistentVolumeClaim:
            claimName: ssd-pvc-echo
        - name: echo-vol-data
          persistentVolumeClaim:
            claimName: data-pvc-echo
      containers:
      - image: busybox
        name: echo
        volumeMounts:
          - mountPath: "/ssd"
            name: echo-vol-ssd
          - mountPath: "/data"
            name: echo-vol-data
        command: ["ping", "127.0.0.1"]
      nodeSelector:
        disk: ssd