#kubectl create deployment nginx --image=nginx
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx #nginx:1.26.0
        ports:
        - containerPort: 80
---
#kubectl create service clusterip nginx --tcp=80:80
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8080 # because else it requires sudo access to create low port number and will be stuck in pending state
      targetPort: 80
      name: http
  #type: ClusterIP
  type: LoadBalancer
