apiVersion: v1
kind: Service
metadata:
  labels:
    service: nextcloud
  name: nextcloud
  namespace:  infra
spec:
  ports:
    - name: "8080"
      protocol: TCP
      port: 8080
      targetPort: 80
    - name: "8089"
      protocol: TCP
      port: 8089
      targetPort: 443
  # update when using ingress
#  type: LoadBalancer
  selector:
    app: nextcloud

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nextcloud
  name: nextcloud
  namespace:  infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      # add this section for built-in Collabora CODE server in Nextcloud
      hostAliases:
      - ip: "192.168.100.205"
        hostnames:
        - nextcloud.local
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            # editing the 'trusted_domains' in /var/www/html/config/config.php
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: "nextcloud.local"
          image: nextcloud
          name: nextcloud
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
          volumeMounts:
            - mountPath: /var/www/html
              name: nextcloud-pvc
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "4Gi"
              cpu: "4"
      nodeSelector:
        disk: ssd
      restartPolicy: Always
      volumes:
        - name: nextcloud-pvc
          persistentVolumeClaim:
            claimName: nextcloud-pvc
---
# Data PV/PVC
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-pv
  labels:
    type: local-ssd
spec:
  storageClassName: manual
  capacity:
    storage: 60Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/ssd/nextcloud"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc
  namespace:  infra
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi
