# make sure the {{ k8s_dir }} folder exists
- name: ensures destination dir exists
  file: 
    path: "{{ work_dir }}/{{ k8s_dir }}"
    state: directory

- name: copy k8s files
  template:
    src: templates/{{ k8s_dir }}/{{ item }}
    dest: "{{ work_dir }}/{{ k8s_dir }}/{{ item }}"
    force: yes
  loop: "{{ k8s_files }}"

- name: Create k8s resources
  shell:
    chdir: "{{ work_dir }}/{{ k8s_dir }}"
    cmd: kubectl apply -f {{ item }}
  loop: "{{ k8s_files }}"
