---
# add files to destination dir
- name: Copy config files to remote
  copy:
    src: "{{ k8s_file }}"
    dest: "{{ work_dir }}/"
    force: yes

# create a k8s ingress
- name: Create an ingress {{ work_dir }}/{{ k8s_file }}
  shell: |
    kubectl apply -f {{ work_dir }}/{{ k8s_file }}
  register: k8s_ingress
  failed_when: k8s_ingress.rc != 1 and k8s_ingress.rc != 0
- name: debug k8s result
  debug:
    msg: "k8s_ingress.rc = {{ k8s_ingress.rc }}"
  when: k8s_ingress
