---
# Data PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv-minio
  labels:
    type: local-hdd
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/minio"

---
# Data PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc-minio
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi

---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  selector:
    app: minio-pod
  ports:
    - name: api
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: console
      protocol: TCP
      port: 9001
      targetPort: 9001
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-app
  labels:
    app: minio
spec:
  replicas: 3
  selector:
    matchLabels:
      app: minio-pod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio-pod
    spec:
      volumes:
        - name: minio-vol-data
          persistentVolumeClaim:
            claimName: data-pvc-minio
      containers:
      - name: minio-docker
        image: billyangbc/minio:alpine-arm
        ports:
          - name: api
            protocol: TCP
            containerPort: 9000
          - name: console
            protocol: TCP
            containerPort: 9001
        env:
          - name: MINIO_ROOT_USER
            value: minio-admin
          - name: MINIO_ROOT_PASSWORD
            value: minio-admin
        command: ["minio"]
        args: ["server", "/data", "--console-address", ":9001"]
        volumeMounts:
          - mountPath: "/data"
            name: minio-vol-data
        resources: {}
        imagePullPolicy: IfNotPresent # This ensures that the image from the local cache is going to be used.
      restartPolicy: Always