#kubectl create deployment nginx --image=nginx
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx #nginx:1.26.0
        ports:
        - containerPort: 80
---
#kubectl create service clusterip nginx --tcp=81:80
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 81 
      targetPort: 80
#      nodePort: 30081
#  type: NodePort
  #type: ClusterIP #with ingress 
  type: LoadBalancer
