# make sure the {{ k8s_dir }} folder exists
- name: ensures destination dir exists
  file: 
    path: "{{ work_dir }}/{{ k8s_dir }}"
    state: directory

- name: copy k8s files
  template:
    src: templates/{{ item }}
    dest: "{{ work_dir }}/{{ k8s_dir }}/{{ item }}"
    force: yes
  loop: "{{ k8s_files }}"

- name: Create and start k8s
  shell:
    chdir: "{{ work_dir }}/{{ k8s_dir }}"
    cmd: kubectl apply -f {{ item }}
  loop: "{{ k8s_files }}"

# add bitnami helm repo
#- name: Add helm repo
#  kubernetes.core.helm_repository:
#      name: "bitnami"
#      repo_url: "https://charts.bitnami.com/bitnami"


# add longhorn helm repo
- name: Add longhorn helm repo
  kubernetes.core.helm_repository:
      name: "{{ helm_repo_name }}"
      repo_url: "{{ helm_chart_url }}"

# install helm chart
- name: Install helm chart
  kubernetes.core.helm:
    namespace: "{{ k8s_namespace }}"
    name: "{{ chart_name }}"
    chart_ref: "{{ chart_ref }}"