---
# ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ k8s_namespace }}
  namespace: {{ k8s_namespace }} # infra
spec:
  ingressClassName: traefik
  rules:
  - host: mongo-express.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mongo-express # mongo-express service name
            port:
              number: 10081
  - host: nextcloud.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nextcloud  # nextcloud service name
            port:
              number: 8080