- name: copy docker-compose
  copy:
    src: files/{{ item.src }}
    dest: "{{ work_dir }}/docker-compose/{{ item.dest }}"
    force: yes
  loop:
    - src: "docker-compose.yml"
      dest: "docker-compose.yml"
    - src: "default.env"
      dest: ".env"
    - src: "postgres-init.sql"
      dest: "postgres-init.sql"
    - src: "newrelic-infra.dockerfile"
      dest: "newrelic-infra.dockerfile"
    - src: "newrelic-infra.yml"
      dest: "newrelic-infra.yml"

- name: Create and start services
  community.docker.docker_compose:
    project_src: "{{ work_dir }}/docker-compose"
    files:
      - docker-compose.yml
  register: output
