- name: Cloud local bootstrap
  hosts: cluster
  gather_facts: true
  roles:
    - {role: bootstrap, become: True}
    - {role: k3d_install, become: True}

- name: Create k3d Cluster
  hosts: cluster
  roles:
    - role: k3d_cluster
      become: False

# create infra in k8s cluster
- name: Create infra namespace in k8s cluster
  hosts: pi5
  roles:
    - role: k8s_infra
      become: False
      vars:
        k8s_files:
          - ns.yaml
          - postgres.yaml
          - redis.yaml
          - mariadb.yaml
          - mongo.yaml
          - mongo-express.yaml
          - nextcloud.yaml
          - ingress.yaml
        k8s_namespace: infra
        k8s_dir: k8s_infra
        nextcloud_ip: 192.168.100.205
        nextcloud_host: nextcloud.local

# create monitor in k8s cluster
- name: Create monitor in k8s cluster
  hosts: pi5
  roles:
    - role: k8s_monitor
      become: False
      vars:
        k8s_files:
          - ns.yaml
          - grafana.yaml
          - prometheus.yaml
          - ingress.yaml
        k8s_namespace: monitor
        k8s_dir: k8s_monitor

# setup longhorn storage in k8s cluster
- name: longhorn storage
  hosts: pi_ai
  roles:
    - role: k8s_helm
      become: False
      vars:
        k8s_namespace: longhorn-system
        k8s_dir: k8s_longhorn
        helm_chart_url: https://charts.longhorn.io
        helm_repo_name: longhorn
        chart_name: longhorn
        chart_ref: longhorn/longhorn
        k8s_files:
          - ns.yaml

- name: Create Storage 
  hosts: pi_nas
  roles:
    - {role: storage, become: False}

# use:
#ansible-playbook -i inventory playbooks/cloud.yml --ask-pass --ask-become-pass
# or:
#ansible-playbook -i inventory playbooks/cloud.yml