# cluster-pi5.yml
---
- hosts: pi5
  roles:
    - { role: bootstrap, become: yes }
    - cluster

#ansible-playbook -i inventory cluster-pi5.yml --ask-pass --ask-become-pass
# use:
#k --kubeconfig=~/.kube/config-pi5
# OR
#export KUBECONFIG=~/.kube/config-pi5